id: P009648
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-19 20:42:44.462898
source_metadata:
  id: bdr:W8LS16390
  title: རྣམ་ཐར་དང་གསུང་སྐོར།
  author: ''
  volumes:
    0cbd6142b3f749c891ce27be36729ff8:
      image_group_id: I8LS16398
      title: ''
      volume_number: 1
      total_pages: 1050
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
