id: P009648
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS16390
  title: རྣམ་ཐར་དང་གསུང་སྐོར།
  author: ''
  volumes:
    0cbd6142b3f749c891ce27be36729ff8:
      image_group_id: I8LS16398
      title: ''
      volume_number: 1
      total_pages: 1050
      base_file: v001.txt
