id: I2928E492
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T19:48:23+00:00'
last_modified: '2022-06-08T12:33:27.613273+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS16390
  title: རྣམ་ཐར་དང་གསུང་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C24C:
      image_group_id: I8LS16398
      title: ''
      total_pages: 1050
      order: 1
      base_file: C24C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
